version: "3.1"

services:
  db:
    container_name: postgres
    image: templo-belen-db
    build:
      context: "postgres/"
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_DB=templo_belen
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer
    restart: unless-stopped
    ports:
      - 8900:8080
    environment:
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: pguser
      ADMINER_PASSWORD: pgpassword
      ADMINER_DB: templo_belen

  server:
    depends_on:
      - db
    image: members-sever-app
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:80
    environment:
      POSTGRES_DB: templo_belen
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      FRONTEND_URL: http://localhost:4200
      SECRET_KEY: changeme
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

volumes:
  db-data:
    driver: local
