services:
  db:
    image: postgres:16.8-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=templo_belen
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db_scripts/:/docker-entrypoint-initdb.d/
  
volumes:
  db-data:
    driver: local
