name: Integration Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Start docker test environment
        run: docker compose -f docker-compose.test.yml up -d

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            docker exec $(docker ps -qf "name=postgres-test") pg_isready && break
            sleep 2
          done

      - name: Run tests
        run: pytest

      - name: Tear down docker test environment
        if: always()
        run: docker compose -f docker-compose.test.yml down -v
